--Ejecutar dentro de sqlplus / as sysdba
ALTER session set "_ORACLE_SCRIPT"=true;
CREATE USER inventario IDENTIFIED BY DBFide1;

GRANT create session TO inventario;
GRANT create table TO inventario;
GRANT create view TO inventario;
GRANT create any trigger TO inventario;
GRANT create any procedure TO inventario;
GRANT create sequence TO inventario;
GRANT create synonym TO inventario;

--Permisos para INSERT https://stackoverflow.com/a/21671145
ALTER USER inventario quota unlimited on USERS;

------------------------------------------------------------
-- Ejecutar en SQLDEVELOPER
-- Tabla "CATEGORÍAS"
CREATE TABLE CATEGORIAS (
ID_CATEGORIA INT PRIMARY KEY,
NOMBRE_CATEGORIA VARCHAR(100)
);

-- Tabla "EQUIPOS"
CREATE TABLE EQUIPOS (
ID_EQUIPO INT PRIMARY KEY,
NOMBRE_EQUIPO VARCHAR(100),
DESCRIPCION VARCHAR(200),
NUM_SERIE VARCHAR(50),
CANTIDAD_DISPONIBLE INT,
CATEGORIA INT,
FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA)
);

-- Tabla "DEPARTAMENTOS"
CREATE TABLE DEPARTAMENTOS (
ID_DEPARTAMENTO INT PRIMARY KEY,
NOMBRE_DEPARTAMENTO VARCHAR(100)
);

-- Tabla "PERSONAL"
CREATE TABLE PERSONAL (
ID_PERSONAL INT PRIMARY KEY,
NOMBRE VARCHAR(100),
TELEFONO VARCHAR(20),
CORREO VARCHAR(100),
ID_DEPARTAMENTO INT,
FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID_DEPARTAMENTO)
);

-- Tabla "ROLES"
CREATE TABLE ROLES (
ID_ROL INT PRIMARY KEY,
NOMBRE VARCHAR(100),
DESCRIPCION VARCHAR(200)
);

-- Tabla "PERMISOS"
CREATE TABLE PERMISOS (
ID_PERMISOS INT PRIMARY KEY,
NOMBRE VARCHAR(100),
ID_ROL INT,
DESCRIPCION VARCHAR(200),
FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL)
);

-- Tabla "PROVEEDORES"
CREATE TABLE PROVEEDORES (
ID_PROVEEDOR INT PRIMARY KEY,
NOMBRE VARCHAR(100),
TELEFONO VARCHAR(20),
CORREO VARCHAR(100)
);

-- Tabla "RECEPCIONES"
CREATE TABLE RECEPCIONES (
ID_RECEPCION INT PRIMARY KEY,
ID_EQUIPO INT,
ID_ALMACEN INT,
FECHA DATE,
HORA TIMESTAMP,
FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS(ID_EQUIPO),
FOREIGN KEY (ID_ALMACEN) REFERENCES ALMACENES(ID_ALMACEN)
);

-- Tabla "ALMACENES"
CREATE TABLE ALMACENES (
ID_ALMACEN INT PRIMARY KEY,
ID_RECEPCION INT,
ID_EQUIPO INT,
NOMBRE_ALMACEN VARCHAR(100),
FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS(ID_EQUIPO)
);

-- Tabla "DESPACHOS"
CREATE TABLE DESPACHOS (
ID_DESPACHO INT PRIMARY KEY,
ID_EQUIPO INT,
ID_DEPARTAMENTO INT,
FECHA DATE,
HORA TIMESTAMP,
ID_PERSONAL INT,
FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS(ID_EQUIPO),
FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID_DEPARTAMENTO),
FOREIGN KEY (ID_PERSONAL) REFERENCES PERSONAL(ID_PERSONAL)
);

-- Tabla "USUARIOS"
CREATE TABLE USUARIOS (
ID_USUARIOS INT PRIMARY KEY,
ID_PERSONAL INT,
USERNAME VARCHAR(100),
PASSWORD VARCHAR(100),
ID_ROL INT,
FOREIGN KEY (ID_PERSONAL) REFERENCES PERSONAL(ID_PERSONAL),
FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL)
);

-- Tabla "COMPRA"
CREATE TABLE COMPRA (
ID_COMPRA INT PRIMARY KEY,
ID_PROVEEDOR INT,
FECHA_COMPRA DATE,
ID_DETALLE_COMPRA INT,
FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR),
FOREIGN KEY (ID_DETALLE_COMPRA) REFERENCES DETALLE_COMPRA(ID_DETALLE_COMPRA)
);

-- Tabla "DETALLE_COMPRA"
CREATE TABLE DETALLE_COMPRA (
ID_DETALLE_COMPRA INT PRIMARY KEY,
MATERIAL VARCHAR(100),
CANTIDAD INT,
PRECIO_UNITARIO DECIMAL(10,2)
);

--SECCION DE INSERTS
--CATEGORIAS
INSERT INTO CATEGORIAS (ID_CATEGORIA, NOMBRE_CATEGORIA)
VALUES (1, 'Categoría 1');

INSERT INTO CATEGORIAS (ID_CATEGORIA, NOMBRE_CATEGORIA)
VALUES (2, 'Categoría 2');

COMMIT;


--Seccion de TRIGGER