--Ejecutar dentro de sqlplus / as sysdba
ALTER session set "_ORACLE_SCRIPT"=true;
CREATE USER inventario IDENTIFIED BY DBFide1;

GRANT create session TO inventario;
GRANT create table TO inventario;
GRANT create view TO inventario;
GRANT create any trigger TO inventario;
GRANT create any procedure TO inventario;
GRANT create sequence TO inventario;
GRANT create synonym TO inventario;
GRANT create trigger TO inventario;

--Permisos para INSERT https://stackoverflow.com/a/21671145
ALTER USER inventario quota unlimited on USERS;

------------------------------------------------------------
-- Ejecutar en SQLDEVELOPER
-- Tabla "CATEGORÍAS"
CREATE TABLE CATEGORIAS (
ID_CATEGORIA INT PRIMARY KEY,
NOMBRE_CATEGORIA VARCHAR(100)
);

-- Tabla "ROLES"
CREATE TABLE ROLES (
ID_ROL INT PRIMARY KEY,
NOMBRE VARCHAR(100),
DESCRIPCION VARCHAR(200)
);

-- Tabla "PERMISOS"
CREATE TABLE PERMISOS (
ID_PERMISOS INT PRIMARY KEY,
NOMBRE VARCHAR(100),
ID_ROL INT,
DESCRIPCION VARCHAR(200),
FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL)
);

-- Tabla "PROVEEDORES"
CREATE TABLE PROVEEDORES (
ID_PROVEEDOR INT PRIMARY KEY,
NOMBRE VARCHAR(100),
TELEFONO VARCHAR(20),
CORREO VARCHAR(100)
);

-- Tabla "ALMACENES"
CREATE TABLE ALMACENES (
ID_ALMACEN INT PRIMARY KEY,
NOMBRE_ALMACEN VARCHAR(100)
);

-- Tabla "EQUIPOS"
CREATE TABLE EQUIPOS (
ID_EQUIPO INT PRIMARY KEY,
NOMBRE_EQUIPO VARCHAR(100),
DESCRIPCION VARCHAR(200),
NUM_SERIE VARCHAR(50),
CANTIDAD_DISPONIBLE INT,
CATEGORIA INT,
FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA)
);

-- Tabla "DEPARTAMENTOS"
CREATE TABLE DEPARTAMENTOS (
ID_DEPARTAMENTO INT PRIMARY KEY,
NOMBRE_DEPARTAMENTO VARCHAR(100)
);

-- Tabla "PERSONAL"
CREATE TABLE PERSONAL (
ID_PERSONAL INT PRIMARY KEY,
NOMBRE VARCHAR(100),
TELEFONO VARCHAR(20),
CORREO VARCHAR(100),
ID_DEPARTAMENTO INT,
FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID_DEPARTAMENTO)
);

-- Tabla "RECEPCIONES"
CREATE TABLE RECEPCIONES (
ID_RECEPCION INT PRIMARY KEY,
ID_EQUIPO INT,
ID_ALMACEN INT,
FECHA DATE,
HORA TIMESTAMP,
FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS(ID_EQUIPO),
FOREIGN KEY (ID_ALMACEN) REFERENCES ALMACENES(ID_ALMACEN)
);

-- Tabla "DESPACHOS"
CREATE TABLE DESPACHOS (
ID_DESPACHO INT PRIMARY KEY,
ID_EQUIPO INT,
ID_DEPARTAMENTO INT,
FECHA DATE,
HORA TIMESTAMP,
ID_PERSONAL INT,
FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS(ID_EQUIPO),
FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID_DEPARTAMENTO),
FOREIGN KEY (ID_PERSONAL) REFERENCES PERSONAL(ID_PERSONAL)
);

-- Tabla "USUARIOS"
CREATE TABLE USUARIOS (
ID_USUARIOS INT PRIMARY KEY,
ID_PERSONAL INT,
USERNAME VARCHAR(100),
PASSWORD VARCHAR(100),
ID_ROL INT,
FOREIGN KEY (ID_PERSONAL) REFERENCES PERSONAL(ID_PERSONAL),
FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL)
);

-- Tabla "COMPRA"
CREATE TABLE COMPRA (
    ID_COMPRA INT PRIMARY KEY,
    ID_PROVEEDOR INT,
    FECHA_COMPRA DATE
);

-- Tabla "DETALLE_COMPRA"
CREATE TABLE DETALLE_COMPRA (
    ID_DETALLE_COMPRA INT PRIMARY KEY,
    MATERIAL VARCHAR(100),
    CANTIDAD INT,
    PRECIO_UNITARIO DECIMAL(10,2),
    ID_COMPRA INT,
    FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA(ID_COMPRA)
);

CREATE VIEW VIEW_DETALLE_COMPRA AS
SELECT ID_DETALLE_COMPRA, MATERIAL, CANTIDAD, PRECIO_UNITARIO, CANTIDAD * PRECIO_UNITARIO AS TOTAL
FROM DETALLE_COMPRA;


CREATE OR REPLACE PROCEDURE procedure_read_detalle_compra(
	   o_c_dbuser OUT SYS_REFCURSOR)
    AS
    BEGIN

      OPEN o_c_dbuser FOR
      SELECT * FROM view_detalle_compra;

    END;

CREATE OR REPLACE PROCEDURE procedure_create_personal(
    p_nombre IN PERSONAL.NOMBRE%TYPE,
    o_c_dbuser OUT SYS_REFCURSOR
)
AS
BEGIN
    INSERT INTO PERSONAL (NOMBRE, TELEFONO, CORREO, ID_DEPARTAMENTO)
    VALUES (p_nombre, '123456789', 'example@example.com', 2);

    OPEN o_c_dbuser FOR
    SELECT *
    FROM PERSONAL
    WHERE NOMBRE = p_nombre;
END;

CREATE OR REPLACE PROCEDURE procedure_read_personal(
    o_c_dbuser OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN o_c_dbuser FOR
    SELECT *
    FROM PERSONAL;
END;


CREATE OR REPLACE PROCEDURE procedure_update_personal(
    p_id_personal IN PERSONAL.ID_PERSONAL%TYPE,
    p_nombre IN PERSONAL.NOMBRE%TYPE,
    p_telefono IN PERSONAL.TELEFONO%TYPE,
    p_correo IN PERSONAL.CORREO%TYPE,
    p_id_departamento IN PERSONAL.ID_DEPARTAMENTO%TYPE,
    o_c_dbuser OUT SYS_REFCURSOR
)
AS
BEGIN
    UPDATE PERSONAL
    SET NOMBRE = p_nombre,
        TELEFONO = p_telefono,
        CORREO = p_correo,
        ID_DEPARTAMENTO = p_id_departamento
    WHERE ID_PERSONAL = p_id_personal;

    OPEN o_c_dbuser FOR
    SELECT *
    FROM PERSONAL
    WHERE ID_PERSONAL = p_id_personal;
END;

CREATE OR REPLACE PROCEDURE procedure_delete_personal(
    p_id_personal IN PERSONAL.ID_PERSONAL%TYPE,
    o_c_dbuser OUT SYS_REFCURSOR
)
AS
BEGIN
    DELETE FROM PERSONAL
    WHERE ID_PERSONAL = p_id_personal;

    OPEN o_c_dbuser FOR
    SELECT *
    FROM PERSONAL
    WHERE ID_PERSONAL = p_id_personal;
END;

--Obtener drop table de todas las tablas
SELECT 'DROP TABLE "' || TABLE_NAME || '" CASCADE CONSTRAINTS;' FROM user_tables;

DROP TABLE "CATEGORIAS" CASCADE CONSTRAINTS;
DROP TABLE "DEPARTAMENTOS" CASCADE CONSTRAINTS;
DROP TABLE "PERSONAL" CASCADE CONSTRAINTS;
DROP TABLE "ROLES" CASCADE CONSTRAINTS;
DROP TABLE "PERMISOS" CASCADE CONSTRAINTS;
DROP TABLE "PROVEEDORES" CASCADE CONSTRAINTS;
DROP TABLE "USUARIOS" CASCADE CONSTRAINTS;
DROP TABLE "EQUIPOS" CASCADE CONSTRAINTS;
DROP TABLE "DESPACHOS" CASCADE CONSTRAINTS;
DROP TABLE "ALMACENES" CASCADE CONSTRAINTS;
DROP TABLE "RECEPCIONES" CASCADE CONSTRAINTS;
DROP TABLE "DETALLE_COMPRA" CASCADE CONSTRAINTS;
DROP TABLE "COMPRA" CASCADE CONSTRAINTS;
